# Issues before testing
1. The db did not initialize with schema.sql script, so every action in UI resulted in error. The breakpoint set at db.py:44 was not reached. Temporarily fixed by manually running script.sql on instance/demo_app.sqlite
2.

# Found problems
1.
